import { Brain, FileEdit, FolderArchive, Mic, Star, User } from 'lucide-react';
import Image from 'next/image';
import React from 'react';

function Card() {
  const details = [
    {
      id: 1,
      title: 'Register Your Account',
      description:
        'Start by creating your account with a quick and easy registration process. Simply sign up and log in to access the full suite of interview practice features.',
      img: <FolderArchive />,
    },
    {
      id: 2,
      title: 'Complete Interview Setup Form',
      description:
        'Fill out a brief form to customize your mock interview. Choose the type of interview, set preferences, and provide any necessary details to tailor the experience to your needs.',
      img: <User />,
    },
    {
      id: 3,
      title: 'Enable Your Microphone',
      description:
        'Activate your microphone to begin the interview. Our platform uses text-to-speech technology to ask you questions, simulating a real interview environment.',
      img: <Mic />,
    },
    {
      id: 4,
      title: 'AI-Generated Questions',
      description:
        'Listen to the questions generated by our AI and respond using your voice. The speech-to-text technology will transcribe your answers in real time.',
      img: <Brain />,
    },
    {
      id: 5,
      title: 'Receive Feedback and Rating',
      description:
        'After completing the interview, our AI evaluates your performance and provides a comprehensive rating along with constructive feedback to help you improve.',
      img: <FileEdit />,
    },
    {
      id: 6,
      title: 'Review and Enhance Your Skills',
      description:
        'Analyze the feedback to understand your strengths and areas for improvement. Use the insights to refine your responses and boost your confidence for real interviews.',
      img: <Star />,
    },
  ];
  return (
    <div className="container mx-auto px-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {details.map((dt) => (
          <div key={dt} className="relative h-64 sm:h-80 lg:h-96">
            <div className="group block h-full overflow-hidden relative">
              <span className="absolute inset-0 border-2 border-dashed border-black"></span>

              <div className="relative flex h-full items-end border-2 border-black bg-white transition-transform transform group-hover:-translate-x-2 group-hover:-translate-y-2">
                <div className="p-4 !pt-0 transition-opacity group-hover:absolute group-hover:opacity-0 sm:p-6 lg:p-8 ">
                  {/* <Image src={dt.img} width={40} height={40} /> */}
                  {dt.img}

                  <h2 className="mt-4 text-xl font-medium sm:text-2xl">{dt.title}</h2>
                </div>

                <div className="absolute inset-0 p-4 opacity-0 transition-opacity group-hover:opacity-100 sm:p-6 lg:p-8">
                  <h3 className="mt-4 text-xl font-medium sm:text-2xl">{dt.title}</h3>

                  <p className="mt-4 text-sm sm:text-base">{dt.description}</p>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default Card;
